{
    "name": "REST Log",
    "summary": "Track REST API calls into DB",
    "version": "17.0.0.0.0",
    "development_status": "Beta",
    "website": "https://github.com/OCA/rest-framework",
    "author": "Camptocamp, ACSONE, Odoo Community Association (OCA)",
    "maintainers": ["simahawk"],
    "license": "LGPL-3",
    "depends": ["base_rest"],
    "data": [
        "data/ir_config_parameter_data.xml",
        "data/ir_cron_data.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/rest_log_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
